"""Parse/merge/write ARCHITECTURE.generated.md sections."""

from __future__ import annotations

import hashlib
import re
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

SECTION_IDS = ("modules", "apis", "dataflow", "integrations")
_SECTION_TITLES = {
    "modules": "Modules",
    "apis": "APIs",
    "dataflow": "DataFlow",
    "integrations": "Integrations",
}

_META_RE = re.compile(
    r"<!--\s*section_id:\s*(\w+)\s*\|\s*hash:\s*([^|]+)\s*\|\s*updated:\s*([^-]+(?:-[^-]+)*)?\s*-->",
    re.I,
)


@dataclass
class ArchSection:
    section_id: str
    title: str
    content: str
    hash: str
    updated: str


def _content_hash(content: str) -> str:
    body = (content or "").strip()
    return "sha256:" + hashlib.sha256(body.encode()).hexdigest()[:16]


def default_doc(project_slug: str = "") -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    slug = project_slug or "unknown"
    lines = [
        "<!-- GENERATED BY ArchitectureCurator — do not edit manually -->",
        f"<!-- project: {slug} | last_full_refresh: {now} -->",
        "",
        "# Architecture (generated)",
        "",
    ]
    for sid in SECTION_IDS:
        title = _SECTION_TITLES[sid]
        lines.extend([
            f"## {title}",
            f"<!-- section_id: {sid} | hash: sha256:pending | updated: {now} -->",
            "",
            "_Not yet generated._",
            "",
        ])
    return "\n".join(lines)


def parse_sections(text: str) -> dict[str, ArchSection]:
    lines = text.splitlines()
    sections: dict[str, ArchSection] = {}
    i = 0
    current_id = ""
    current_title = ""
    meta_hash = ""
    meta_updated = ""
    content_lines: list[str] = []

    def flush() -> None:
        nonlocal current_id, content_lines
        if current_id:
            content = "\n".join(content_lines).strip()
            sections[current_id] = ArchSection(
                section_id=current_id,
                title=current_title or _SECTION_TITLES.get(current_id, current_id),
                content=content,
                hash=meta_hash or _content_hash(content),
                updated=meta_updated,
            )
        content_lines = []

    while i < len(lines):
        line = lines[i]
        if line.startswith("## "):
            title = line[3:].strip()
            sid_match = None
            for sid, stitle in _SECTION_TITLES.items():
                if title.lower() == stitle.lower():
                    sid_match = sid
                    break
            if sid_match:
                flush()
                current_title = title
                current_id = sid_match
                meta_hash = ""
                meta_updated = ""
                i += 1
                if i < len(lines):
                    m = _META_RE.match(lines[i].strip())
                    if m:
                        current_id = m.group(1).lower()
                        meta_hash = m.group(2).strip()
                        meta_updated = (m.group(3) or "").strip()
                        i += 1
                continue
        if current_id or current_title:
            content_lines.append(line)
        i += 1
    flush()
    return sections


def merge_section(doc_path: Path, section_id: str, new_content: str, *, project_slug: str = "") -> ArchSection:
    sid = section_id.lower()
    if sid not in SECTION_IDS:
        raise ValueError(f"Unknown section_id: {section_id}")
    if doc_path.is_file():
        text = doc_path.read_text(encoding="utf-8")
    else:
        doc_path.parent.mkdir(parents=True, exist_ok=True)
        text = default_doc(project_slug)
    sections = parse_sections(text)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    h = _content_hash(new_content)
    sections[sid] = ArchSection(
        section_id=sid,
        title=_SECTION_TITLES[sid],
        content=new_content.strip(),
        hash=h,
        updated=now,
    )
    write_doc(doc_path, sections, project_slug=project_slug)
    return sections[sid]


def write_doc(doc_path: Path, sections: dict[str, ArchSection], *, project_slug: str = "") -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    slug = project_slug or "unknown"
    lines = [
        "<!-- GENERATED BY ArchitectureCurator — do not edit manually -->",
        f"<!-- project: {slug} | last_full_refresh: {now} -->",
        "",
        "# Architecture (generated)",
        "",
    ]
    for sid in SECTION_IDS:
        sec = sections.get(sid)
        if not sec:
            sec = ArchSection(sid, _SECTION_TITLES[sid], "_Not yet generated._", "sha256:pending", now)
        lines.extend([
            f"## {sec.title}",
            f"<!-- section_id: {sid} | hash: {sec.hash} | updated: {sec.updated or now} -->",
            "",
            sec.content,
            "",
        ])
    atomic_write(doc_path, "\n".join(lines))


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", delete=False, dir=str(path.parent), suffix=".tmp") as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    tmp_path.replace(path)


def read_doc(doc_path: Path) -> str:
    if not doc_path.is_file():
        return default_doc()
    return doc_path.read_text(encoding="utf-8")
